### ISSUE TITLE
Trimming option

### ISSUE THREAD

**Issue by Nucleus12** [nanoporetech/qcat#1]
Hi,

I gave a try to QCAT last week and used the --trim option but the barcodes were still present on the reads after demultiplexing.  Is this a bug or just not implemented yet?

Also, it would be great if QCAT could have a bit more flexibility in term of %identity matches to find barcodes.

Very promising so far, faster than Porechop in my initial test.

**Comment by philres** [comment]
Hi!

Thank you for message! Could you please send me a couple of reads that did not get trimmed properly. I just tried and could not reproduce the problem myself on the data I used.

**Comment by philres** [comment]
Hi Pascal,

I'm afraid a file attached to an e-mail reply is not uploaded automatically by github so I couldn't give it a try using your reads.

However, could you please try running qcat again as follows:
```
~/miniconda3/bin/qcat -f sub.fastq -b ./ --trim --detect-middle
```
Currently, you have to activate trimming by using ```--trim```.
If you want you can skip ```-k Auto``` as it is the default value.
About ```-t```. It is currently not implemented so you can skip it. Quick question, did you get a warning that multi threading is not yet supported?
In any way, qcat should be considerably faster then porechop so running with a single thread should still be quick.

Hope that helped. Please let me know if you have any issues running this command.

Thanks,
Philipp

**Comment by philres** [comment]
One thing I missed.

Qcat assigns a quality score to a barcoding call. The score is between 0 and 100. Similar, to identity in porechop but not exactly the same. The default minimum score is 60. Meaning every barcoding call with a quality < 60 will not be reported. ```-q/--min-quality``` changes this cutoff. Increasing it to values > 60 will reduce the incorrect rate but increase the unclassified rate. Changing it to values < 60 will have the opposite effect. I would recommend to use the default value. Meaning not to set ```-q/--min-quality```.

This should not be confused with ONT's average base quality score. That is why I removed ```-q 7``` from your call. I will update the README and might change the name of the parameter to make that clearer.

**Comment by Nucleus12** [comment]
Sorry I did not put it up there but I had used the --trim option.

I have reran the command line you send and it did trimmed the barcodes this time.  I must have done something different the first time.

As for the -q flag, you are right, I thought it was for the Phred score.  

Thanks philres
