### ISSUE TITLE
Opening demultiplexed fastq files

### ISSUE THREAD

**Issue by kshitijsri82** [nanoporetech/qcat#11]
Hi

After demultiplexing, I am unable to open the individual files using word. However, the output fastq file from the gridion was opening fine in word.

Thanks

**Comment by philres** [comment]
Hi,

The most likely reason is that the demultiplexed FASTQ files contain too many reads too load. FASTQ files from the basecaller contain only 4000 reads each. The demultiplexed FASTQ files on the other hand contain all reads from a given run for a single barcode (potentially several GB).

In general I would not recommend opening FASTQ files with Word or any other graphical text editor.
I would recommend `less` or `head` and `tail` on the command line as those tools allow you to inspect arbitrarily large files. These tools are available on Mac and Linux. I would recommend using one of the two if you want to work with sequencing data efficiently.
In case you want to stick to Windows you could try cygwin or Windows subsytem for Linux.

Hope that helps,
Philipp
