### ISSUE TITLE
fastq chunks

### ISSUE THREAD

**Issue by dridk** [nanoporetech/qcat#20]
Hi,

I have an input folder with many fastq file with the same line number. I suppose the guppy outputs reads as chunks. 
Is the following line okay ? 
```
 cat *.fastq > all.fastq
qcat -f all.fastq -d demultiplexing ? 
```

Otherwise, it would be greate to have a command line argument which takes folder as input

**Comment by philres** [comment]
Hi!

You can do:

cat *.fastq | qcat -d demultiplexing

Hope that helps,
Philipp
