### ISSUE TITLE
--tsv conflict with -b <output>

### ISSUE THREAD

**Issue by cgjosephlee** [nanoporetech/qcat#7]
I install qcat via lastest git clone manually, version 1.0.2.

`cat *fastq | qcat -b qcat_1.0.2_trim -k PBK004/LWB001 --trim --detect-middle --tsv > log` ended up nothing in `qcat_1.0.2_trim`.
Removes `--tsv` and it works as expected.

**Comment by philres** [comment]
Thanks, will have a look at this

**Comment by philres** [comment]
Thanks again for reporting this and sorry for the delay, should be fixed on master now. Will be in the next release on conda.

**Comment by cgjosephlee** [comment]
Great thanks.

**Comment by TomHarrop** [comment]
Hi, if you fixed this, can you please tag a new release?

I'm having the same problem with the latest release on github / pip (v1.0.1)
