### ISSUE TITLE
--trim returns zero-length read

### ISSUE THREAD

**Issue by cgjosephlee** [nanoporetech/qcat#8]
`--trim` works fine but in only one case it returns an empty record with zero-length read.
```
@6dde8a3c-f7c8-41a7-9b0f-010d25df5452 runid=5ac92691e6bec89a27e0195de74642bd375db73a sampleid=L3-Adult read=39833 ch=352 start_time=2018-11-10T18:39:03Z

+
```
Maybe we should have a minimal length cutoff?

**Comment by philres** [comment]
Thanks for reporting this. We will add a minimal read length.

Philipp

**Comment by philres** [comment]
I added a `--min-read-length` option to qcat which is set to 100 per default. The changes are here on the master branch (if you want to give it a try) and will go into the next release.

**Comment by philres** [comment]
I added a `--min-read-length` option to qcat which is set to 100 per default. The changes are here on the master branch (if you want to give it a try) and will go into the next release.
